#ifndef EXYNOS_CAMERA_TUNING_COMMAND_ID_LIST_H__
#define EXYNOS_CAMERA_TUNING_COMMAND_ID_LIST_H__

typedef enum
{

    SIMMYCMD_NO_CMD = 0x00,

    /** Information & debug */
    //!@{
    SIMMYCMD_GET_FW_VER = 0x01,
    SIMMYCMD_GET_SIRC_SDK_VER = 0x02,
    SIMMYCMD_GET_TUNESETFILE_VER = 0x03,
    SIMMYCMD_GET_SHARED_REGION_INFO = 0x04,
    SIMMYCMD_SET_DEBUG_MSG = 0x05,
    SIMMYCMD_GET_SENSOR_INFO = 0x06,
    SIMMYCMD_GET_SYSTEM_INFO = 0x07,
    SIMMYCMD_GET_ISP_FRAMEDESCRIPTOR = 0x08,
    SIMMYCMD_GET_HOST_VER = 0x09,
    SIMMYCMD_GET_A5_LOG = 0x0a,
    SIMMYCMD_GET_ISPTUNERAW_SETFILEV3 = 0x0b,
    SIMMYCMD_GET_HOST_LOG = 0x0c,
    SIMMYCMD_SET_CURRENT_TIME = 0x0d,
    //!@}

    /** System Control  */
    //!@{
    SIMMYCMD_SET_POWER_OFF = 0x100,
    SIMMYCMD_SET_POWER_ON = 0x101,
    SIMMYCMD_SET_FW_LOAD = 0x102,
    SIMMYCMD_SET_TUNESET_LOAD = 0x103,
    SIMMYCMD_SET_FW_RESET = 0x104,
    SIMMYCMD_SET_SENSOR_SELECT = 0x105,
    SIMMYCMD_SET_FW_START = 0x106,
    SIMMYCMD_SET_MODE_CHANGE = 0x107,
    SIMMYCMD_GET_MODE_CHANGE = 0x108,
    SIMMYCMD_SET_CURRENT_SENSOR_FPS_CHANGE = 0x109,
    //  SIMMYCMD_SET_SIMMIAN_IMAGE_SOURCE       = 0x110,
    SIMMYCMD_SET_MEDIA_STORE_DEVICE = 0x111,
    SIMMYCMD_SET_LCDBACKLIGHT_ONOFF = 0x112,
    SIMMYCMD_SET_SIMMIAN_SRC_CHANGE = 0x113,
    SIMMYCMD_UPDATE_SENSOR_INFO = 0x114,
    SIMMYCMD_CHANGE_ZOOM_FACTOR = 0x115,
    SIMMYCMD_SET_EMMC_FUSING = 0x116,
    SIMMYCMD_GET_FROM_DATA = 0x117,
    SIMMYCMD_WRITE_FROM_DATA = 0x118,        /**< Coming from Carmen, GAIA    */
    SIMMYCMD_ERASE_ALL_FROM_DATA = 0x119,        /**< Coming from Carmen, GAIA    */
    SIMMYCMD_CHECK_FROM_ID = 0x11A,        /**< Coming from Carmen, GAIA    */
    SIMMYCMD_SET_DZOOM_ON_OFF = 0x11B,        /**< Adonis, Ares, Helsinki      */
    SIMMYCMD_SET_FW_STOP = 0x11C,
    SIMMYCMD_SET_SENSOR_MODE_CHANGE = 0x11D,    // Added by payton (sehoon.kim) 20151020 - For supporting Simmian Preview in Joshua project
    SIMMYCMD_LOAD_COMPANION_FW = 0x180,
    SIMMYCMD_LOAD_COMPANION_MASTER_SETFILE = 0x181,
    SIMMYCMD_LOAD_COMPANION_MODE_SETFILE = 0x182,
    SIMMYCMD_SET_COMPANION_CTRL = 0x183,
    SIMMYCMD_GET_COMPANION_CTRL = 0x184,
    SIMMYCMD_READ_FROM = 0x185,
    SIMMYCMD_WRITE_FROM = 0x186,
    SIMMYCMD_FROM_BUF_ALLOC = 0x187,
    SIMMYCMD_READ_EEPROM = 0x188,
    SIMMYCMD_WRITE_EEPROM = 0x189,
    SIMMYCMD_SET_COMPANION_BYPASS = 0x18A,
    SIMMYCMD_GET_COMPANION_BYPASS = 0x18B,
    SIMMYCMD_GENERAL_I2C_ACCESS_DATA = 0x18C,
    SIMMYCMD_REQUEST_BUFFER_FOR_GERNEAL_I2C_ACCESS = 0x18D,
    //!@}

#ifdef APACCESS_MP_SUPPORT// for JIG CAM power control
    SIMMYCMD_SET_CAM_POWER_ON = 0xA001,
    SIMMYCMD_SET_CAM_POWER_OFF = 0xA002,
#endif

    /** ISP Command   */
    //!@{
    SIMMYCMD_SET_ISP_START_STOP = 0x200,
    SIMMYCMD_SET_ISP_USERMAXFRAMETIME = 0x201,
    SIMMYCMD_SET_ISP_YUV_DMAOUT = 0x202,
    SIMMYCMD_SET_ISP_BAYER_DMAOUT = 0x203,

    SIMMYCMD_SET_ISP_CAPTURE_JPEG = 0x210,
    SIMMYCMD_SET_ISP_CAPTURE_YUV = 0x211,
    SIMMYCMD_SET_ISP_CAPTURE_BAYER = 0x212,
    SIMMYCMD_SET_ISP_CAPTURE_BMP = 0x213,
    SIMMYCMD_SET_ISP_TRANSFER_JPEGQTABLE_DATA = 0x214,

    SIMMYCMD_SET_ISP_START_MFCENCODING = 0x215,
    SIMMYCMD_GET_ISP_MFC_STATUS = 0x216,
    SIMMYCMD_SET_ISP_SAVE_MFCENCODING = 0x217,
    SIMMYCMD_GET_FIMC_LITE_SCC_BUFFER = 0x218, // Added by payton (sehoon.kim) 20140725 - For supporting the same frame capture

    SIMMYCMD_SET_ISP_AWB = 0x280,
    SIMMYCMD_SET_ISP_EFFECT = 0x281,
    SIMMYCMD_SET_ISP_ISO = 0x282,
    SIMMYCMD_SET_ISP_ADJUST = 0x283,
    SIMMYCMD_SET_ISP_EXPOSURE_CONTROL = 0x284,
    SIMMYCMD_SET_ISP_AE_METERING = 0x285,
    SIMMYCMD_SET_ISP_AFC = 0x286,
    SIMMYCMD_SET_ISP_LOCK_AWB_AE = 0x287,
    SIMMYCMD_SET_ISP_FLASH = 0x288,
    SIMMYCMD_SET_ISP_SCENEMODE = 0x289,
    SIMMYCMD_SET_ISP_FLASH_SCENARIO = 0x290,
    SIMMYCMD_SET_ISP_3A_MODE = 0x291,
    SIMMYCMD_SET_ISP_3AAE_MODE = 0x292,
    SIMMYCMD_GET_NOISE_REDUCTION = 0x293, // Added by payton (sehoon.kim) 20150603 - For supporting new noiseReduction interface
    SIMMYCMD_SET_NOISE_REDUCTION = 0x294, // Added by payton (sehoon.kim) 20150603 - For supporting new noiseReduction interface
    SIMMYCMD_GET_EDGE_ENHANCEMENT = 0x295,// Added by payton (sehoon.kim) 20150603 - For supporting new edgeEnhancement interface
    SIMMYCMD_SET_EDGE_ENHANCEMENT = 0x296,// Added by payton (sehoon.kim) 20150603 - For supporting new edgeEnhancement interface
    SIMMYCMD_GET_IP_STATUS = 0x2A0,
#if (SCALER_YUV_RANGE == 1)
    SIMMYCMD_SET_YUV_RANGE = 0x2B0,
#endif
    SIMMYCMD_SET_WDR_COMMAND = 0x2B1,
    //!@}

    /** AF */
    //!@{
    SIMMYCMD_AF_CHANGE_MODE = 0x1000,
    SIMMYCMD_AF_SET_WINDOW = 0x1001,
    SIMMYCMD_AF_GET_WINDOW_START_POSITION = 0x1002,
    SIMMYCMD_AF_GET_WINDOW_SIZE = 0x1003,
    SIMMYCMD_AF_GET_GRAD1 = 0x1004,
    SIMMYCMD_AF_GET_GRAD2 = 0x1005,
    SIMMYCMD_AF_GET_HPF = 0x1006,
    SIMMYCMD_AF_GET_FILTER_3x9 = 0x1007,
    SIMMYCMD_AF_GET_CLIP_COUNTER = 0x1008,
    SIMMYCMD_AF_GET_Y_SUM = 0x1009,
    SIMMYCMD_AF_GET_FILTER_1x17 = 0x100A,
    SIMMYCMD_AF_GET_LENS_POSITION = 0x100B,
    SIMMYCMD_AF_SET_ONSCRREN_AF_WINDOW = 0x100C,
    SIMMYCMD_AF_GET_WINDOW = 0x100D,
    SIMMYCMD_AF_GET_FOCUS_STATUS = 0x100E,
    //!@}

    /** DRC */
    //!@{
    SIMMYCMD_SET_DRC_START_STOP = 0x2000,
    SIMMYCMD_GET_DRC_SETFILE_ADDRESS = 0x2001,
    SIMMYCMD_SET_DRC_UPDATE = 0x2002,
    //!@}

    /** TDNR  */
    //!@{
    SIMMYCMD_SET_3DNR_START_STOP = 0x2300,
    SIMMYCMD_GET_3DNR_SETFILE_ADDRESS = 0x2301,
    SIMMYCMD_SET_TDNR_UPDATE = 0x2302,
    //!@}

    /** MCSC */
    //!@{
    SIMMYCMD_SET_MCSC_FLIP_CONTROL = 0x2400,
    //!@}

    /**DIS  */
    //!@{
    SIMMYCMD_SET_DIS_START_STOP = 0x2600,
    SIMMYCMD_GET_DIS_SETFILE_ADDRESS = 0x2601,
    //!@}

    /**FD */
    //!@{
    SIMMYCMD_SET_FD_START_STOP = 0x3000,
    SIMMYCMD_SET_FD_MAX_NUM = 0x3001,
    SIMMYCMD_SET_FD_ROLL_ANGLE = 0x3002,
    SIMMYCMD_SET_FD_YAW_ANGLE = 0x3003,
    SIMMYCMD_SET_FD_ORIENTATION = 0x3004,
    SIMMYCMD_SET_FD_SMILE_MODE = 0x3005,
    SIMMYCMD_SET_FD_BLINK_MODE = 0x3006,
    SIMMYCMD_SET_FD_EYES_DECTECT = 0x3007,
    SIMMYCMD_SET_FD_MOUTH_DECTECT = 0x3008,
    SIMMYCMD_GET_FD_SETFILE_ADDRESS = 0x3009,
    SIMMYCMD_SET_FD_UPDATE = 0x300A,
    //!@}

    /**TPU */
    //!@{
    SIMMYCMD_SET_TPU_START_STOP = 0x3100,
    SIMMYCMD_GET_TPU_SETFILE_ADDRESS = 0x3101,
    SIMMYCMD_SET_TPU_UPDATE = 0x3102,
    //!@}

    /**VRA */
    SIMMYCMD_SET_VRA_START_STOP = 0x3200,
    SIMMYCMD_GET_VRA_SETFILE_ADDRESS = 0x3201,
    SIMMYCMD_SET_VRA_UPDATE = 0x3202,
    SIMMYCMD_SET_VRA_ORIENTATION = 0x3203,
    //!@}

    /** Emulation   */
    //!@{
    SIMMYCMD_SET_EMULATOR_START = 0x4000,
    SIMMYCMD_SET_EMULATOR_STOP = 0x4001,
    SIMMYCMD_SET_EMULATOR_PARAMETERS = 0x4002,

    SIMMYCMD_SET_APACCESS_JSON_3A_REINIT = 0x4011,
    SIMMYCMD_SET_APACCESS_JSON_READ_BY_TUNEID = 0x4012,
    SIMMYCMD_SET_APACCESS_JSON_WRITE_WITH_BUFFER = 0x4013,

    SIMMYCMD_GET_APACCESS_EMULATOR_BUFFER_ADDR = 0x40020,
    SIMMYCMD_GET_APACCESS_EMULATOR_BUFFER_CAPTURE_TO_SD_CARD = 0x40021,

    SIMMYCMD_GET_JSON_TARGET_ISP = 0X4100,
    SIMMYCMD_SET_JSON_TARGET_ISP = 0X4101,
    //!@}

#ifdef APACCESS_MP_SUPPORT
    /** for APAccessMP  */
    //!@{
    SIMMYCMD_TEST_FW_START = 0x4500,


    SIMMYCMD_TEST_LOAD_ISP_FW_WITHPATH = 0x4510,
    SIMMYCMD_TEST_LOAD_ISP_SETFILE_WITHPATH = 0x4511,

    SIMMYCMD_TEST_LOAD_73C1_0_FW_WITHPATH = 0x4512,          /**< for 73c1 EVT0          */
    SIMMYCMD_TEST_LOAD_73C1_0_MASTE_SETFILE_WITHPATH = 0x4513,
    SIMMYCMD_TEST_LOAD_73C1_0_MODE_SETFILE_WITHPATH = 0x4514,
    SIMMYCMD_TEST_LOAD_73C1_1_FW_WITHPATH = 0x4515,          /**< for 73c1 EVT1          */
    SIMMYCMD_TEST_LOAD_73C1_1_MASTE_SETFILE_WITHPATH = 0x4516,
    SIMMYCMD_TEST_LOAD_73C1_1_MODE_SETFILE_WITHPATH = 0x4517,

    SIMMYCMD_TEST_SET_I2C_DRIVE_CONTROL = 0x4520,      // JIG I2C,SPI SlewRate & Drive Strength Control

    SIMMYCMD_TEST_PREVIEW = 0x5000,
    SIMMYCMD_TEST_RESET_CAMERA = 0x6000,
    SIMMYCMD_TEST_RESET_AP = 0x6001,
    SIMMYCMD_TEST_ETC_AE_LOCK_UNLOCK = 0x6002,
    SIMMYCMD_TEST_ETC_AWB_LOCK_UNLOCK = 0x6003,
    SIMMYCMD_TEST_ETC_SHADING_ON_OFF = 0x6004,
    SIMMYCMD_TEST_ETC_SET_SPICLK = 0x6005,
    SIMMYCMD_TEST_ETC_BCP_ON_OFF = 0x6006,
    SIMMYCMD_TEST_ETC_EV_CONTROL = 0x6007,
    SIMMYCMD_TEST_ETC_PDAF_SENSOR_CONTROL = 0x6008,                 /**< PDAF control at sensor(2P2) */
    SIMMYCMD_TEST_ETC_SENSOR_I2C_READ_DATA = 0x6009,
    SIMMYCMD_TEST_ETC_SENSOR_I2C_WRITE_DATA = 0x600a,
    SIMMYCMD_TEST_ETC_SENSOR_I2C_READ_BURST = 0x600b,
    SIMMYCMD_TEST_ETC_SENSOR_I2C_WRITE_BURST = 0x600c,
    SIMMYCMD_TEST_ETC_GENERAL_I2C_ACCESS_DATA = 0x6010,

    SIMMYCMD_TEST_ETC_73Cx_WDR_ONOFF = 0x6100,
    SIMMYCMD_TEST_ETC_73Cx_BYPASS_ONOFF = 0x6101,
    //!@}

    /**AF  */
    //!@{
    SIMMYCMD_TEST_ETC_AF_MODE = 0x7000,
    SIMMYCMD_TEST_ETC_AF_POS_GET = 0x7001,
    SIMMYCMD_TEST_ETC_AF_POS_SET = 0x7002,
    SIMMYCMD_TEST_ETC_AF_STATUS_GET = 0x7003,
    SIMMYCMD_TEST_ETC_AF_SCORE_GET = 0x7004,
    SIMMYCMD_TEST_ETC_AF_LIB_VER_GET = 0x7005,
    SIMMYCMD_TEST_ETC_ACTUATOR_SELECT = 0x7006,
    SIMMYCMD_TEST_ETC_AF_WINDOW_STAT_GET = 0x7007,
    SIMMYCMD_TEST_ETC_AF_PDAF_STAT_GET = 0x7008,
    SIMMYCMD_TEST_ETC_AF_TOUCH_SET = 0x7009,
    SIMMYCMD_TEST_ETC_AF_WINDOW_CORDINATE_GET = 0x700a,
    //!@}

    /** FROM general */
    //!@{
    SIMMYCMD_TEST_ETC_FROM_DATA_ERASE = 0x7100,                      /**< by address/size    */
    SIMMYCMD_TEST_ETC_FROM_DATA_READ = 0x7101,                      /**< by address/size    */
    SIMMYCMD_TEST_ETC_FROM_DATA_WRITE = 0x7102,                      /**< by address/size    */
    SIMMYCMD_TEST_ETC_FROM_CHECK_CONNECT = 0x7103,
    //!@}


    /** EEPROM general , 20140403 SC KIM    */
    SIMMYCMD_TEST_ETC_EEPROM_ACCESS_DATA = 0x7200,

    //FROM
    /** OPTICS Command  */
    //!@{
    SIMMYCMD_TEST_ETC_ACTUATOR_CALIBATE_OPTICS = 0x7500,
    SIMMYCMD_TEST_ETC_READ_EQUIPMENT_INFO_OPTICS,
    SIMMYCMD_TEST_ETC_WRITE_EQUIPMENT_INFO_OPTICS,
    SIMMYCMD_TEST_ETC_WRITE_DATA_IN_FROM_OPTICS,
    SIMMYCMD_TEST_ETC_READ_OEM_DATA_OPTICS,
    SIMMYCMD_TEST_ETC_WRITE_OEM_DATA_OPTICS,
    //!@}

    /** ELECT Command   */
    //!@{
    SIMMYCMD_TEST_ETC_ACTUATOR_CALIBATE_ELEC = 0x7550,
    SIMMYCMD_TEST_ETC_READ_EQUIPMENT_INFO_ELEC,
    SIMMYCMD_TEST_ETC_WRITE_EQUIPMENT_INFO_ELEC,
    SIMMYCMD_TEST_ETC_WRITE_DATA_IN_FROM_ELEC,
    SIMMYCMD_TEST_ETC_READ_OEM_DATA_ELEC,
    SIMMYCMD_TEST_ETC_WRITE_OEM_DATA_ELEC,
    //!@}

    /** Common commands */
    //!@{
    SIMMYCMD_TEST_ETC_WRITE_HEADER_DATA = 0x75A0,
    SIMMYCMD_TEST_ETC_WRITE_AWB_DATA,
    SIMMYCMD_TEST_ETC_WRITE_SHADING_DATA,
    SIMMYCMD_TEST_ETC_READ_HEADER_DATA,
    SIMMYCMD_TEST_ETC_WRITE_FW_SETFILE_INFO,
    SIMMYCMD_TEST_ETC_WRITE_FW_SETFILE,
    SIMMYCMD_TEST_ETC_READ_AWB_DATA,
    SIMMYCMD_TEST_ETC_READ_SHADING_DATA,
    SIMMYCMD_TEST_ETC_READ_DATA_IN_FROM,
    SIMMYCMD_TEST_ETC_WRITE_DATA_IN_FROM,
    SIMMYCMD_TEST_ETC_REQUEST_BUFFER_FOR_FROM,
    SIMMYCMD_TEST_ETC_FREE_BUFFER_FOR_FROM,

    SIMMYCMD_TEST_ETC_GET_FW_VERSION,
    SIMMYCMD_TEST_ETC_GET_SETFILE_VERSION,
    SIMMYCMD_TEST_ETC_GET_FW_VERSION_FromSD,
    SIMMYCMD_TEST_ETC_GET_SETFILE_VERSION_FromSD,
    //!@}

    /** AF I2C Command */
    //!@{
    SIMMYCMD_TEST_ETC_AF_I2C_WRITE_DATA = 0x7600,
    SIMMYCMD_TEST_ETC_AF_I2C_READ_DATA = 0x7601,
    //!@}

    /** OSI I2C Command */
    //!@{
    SIMMYCMD_TEST_ETC_OIS_I2C_WRITE_DATA = 0x7602,
    SIMMYCMD_TEST_ETC_OIS_I2C_READ_DATA = 0x7603,
    //!@}

    /** Sensor I2C Command */
    SIMMYCMD_TEST_ETC_SENSOR_I2C_READ_FUSE_ID = 0x7630,

    /** Sensor I2C Check Command */
    SIMMYCMD_TEST_ETC_SENSOR_I2C_CHECK = 0x7631,

    /** AF I2C Check Command */
    SIMMYCMD_TEST_ETC_AF_I2C_CHECK = 0x7632,

    /** Commands of the new code structure for V1 and later */
    //!@{
    SIMMYCMD_TEST_ETC_ACTUATOR_CALIBATE = 0x7650,
    SIMMYCMD_TEST_ETC_READ_EQUIPMENT_INFO,
    SIMMYCMD_TEST_ETC_WRITE_EQUIPMENT_INFO,
    SIMMYCMD_TEST_ETC_WRITE_ALL_SECTIONS,
    //!@}

    SIMMYCMD_TEST_ETC_WRITE_HEADER,
    SIMMYCMD_TEST_ETC_WRITE_OEM,
    SIMMYCMD_TEST_ETC_WRITE_AWB,
    SIMMYCMD_TEST_ETC_WRITE_SHADING,
    SIMMYCMD_TEST_ETC_READ_HEADER,
    SIMMYCMD_TEST_ETC_READ_OEM,
    SIMMYCMD_TEST_ETC_READ_AWB,
    SIMMYCMD_TEST_ETC_READ_SHADING,
    SIMMYCMD_TEST_ETC_WRITE_FW_SETFILE_INFO_COMMON,
    SIMMYCMD_TEST_ETC_WRITE_FW_SETFILE_COMMON,
    SIMMYCMD_TEST_ETC_GET_FW_VERSION_COMMON,
    SIMMYCMD_TEST_ETC_GET_SETFILE_VERSION_COMMON,
#endif  // APACCESS_MP_SUPPORT

}tSubCommandId;

#endif //EXYNOS_CAMERA_TUNING_COMMAND_ID_LIST_H__
